### ISSUE TITLE
Using with new CSF format

### ISSUE THREAD

**Issue by MartinYW** [santino/storybook-found-router#1]
Hi,
first of all thanks for this library. That's exactly what I need now!

Anyway I use new [CSF format](https://storybook.js.org/docs/formats/component-story-format/) for writing stories and I can't make it working. I tried to wrap my component with your decorator as HOC without success. Am I missing something?

**Comment by santino** [comment]
Hi Martin,
glad to hear the library is useful to you as well.

I also use the new CSF format in my project with found 0.4.0 and Storybook 5.3.10 and all is working as expected.

Not sure how you are setting up the decorator; maybe you can share some code.

Personally I'm setting the decorator globally to all my stories with a routeConfig array; this is what I have in my `preview.js`:
```js
import storyRouter from 'storybook-found-router'

const routeConfig = [
  {
    path: '/',
    story: 'Pages/HomePage',
    children: [
      {
        path: 'login',
        story: 'Pages/LoginPage'
      },
      {...}
    ]
  }
]

addDecorator(storyRouter(routeConfig))
```

Benefit is that I can also navigate through stories when I have links, since `storybook-found-router` will push to the matched stories.

I also just double checked that setting the decorator individually within stories is also working as expected even using CSF; here is a snippet:
```js
import React from 'react'
import storyRouter from 'storybook-found-router'

export default {
  title: 'Pages/HomePage'
}

export const Default = () => <div>My Home Page story</div>

Default.story = {
  name: 'default',
  decorators: [storyRouter()]
}
```

Hope this helps; otherwise feel free to share more about your config.

**Comment by MartinYW** [comment]
Hey it works! I used wrong syntax in `decorators` array. :) Thanks for super quick response! 👍
